-- MySQL Script generated by MySQL Workbench
-- Wed Mar  6 15:44:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ewoman
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ewoman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ewoman` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `db_ewoman` ;

-- -----------------------------------------------------
-- Table `db_ewoman`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ewoman`.`categoria` (
  `idcategoria` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ewoman`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ewoman`.`produtos` (
  `idprodutos` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `custo` FLOAT NOT NULL,
  `vagas` INT NULL,
  `taxas` INT NULL,
  `categoria_idcategoria` BIGINT NOT NULL,
  PRIMARY KEY (`idprodutos`),
  INDEX `fk_produtos_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `db_ewoman`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ewoman`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ewoman`.`usuario` (
  `idusuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `produtos_idprodutos` BIGINT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_produtos1_idx` (`produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `db_ewoman`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO produtos (nome_produto, preco, custo, vagas, taxas, categoria_idcategoria) VALUES
('Plano Gratuito', 0, 50, 100, 0.05, 1),
('Plano Gratuito', 0, 50, 100, 0.05, 2),
('Plano Gratuito', 0, 50, 100, 0.05, 3),
('Plano Pago 1', 0, 50, 100, 0.05, 4),
('Plano Pago 1', 0, 50, 100, 0.05, 5),
('Plano Pago 1', 0, 50, 100, 0.05, 6),
('Plano Pago 2', 0, 50, 100, 0.05, 7),
('Plano Pago 2', 0, 50, 100, 0.05, 8),
('Plano Pago 2', 0, 50, 100, 0.05, 9);

INSERT INTO categoria (nome_categoria, nivel) VALUES
('Cosméticos', 'Iniciante'),
('Moda', 'Iniciante'),
('Eletrônicos', 'Iniciante'),
('Cosméticos', 'Intermediario'),
('Moda', 'Intermediario'),
('Eletrônicos', 'Intermediario'),
('Cosméticos', 'Avançado'),
('Moda', 'Avançado'),
('Eletrônicos', 'Avançado');

INSERT INTO usuario (nome_usuario, email_usuario, foto, senha, produtos_idprodutos) VALUES
('Maria da Silva', 'maria123@gmail.com', 'S', 123456, 1),
('Ana Souza', 'ana.souza@hotmail.com', 'S', 567890, 3),
('Fernanda Lima', 'fernanda.lima@gmail.com', 'S', 876543, 5),
('Camila Pereira', 'camila.pereira@hotmail.com', 'S', 234567, 7),
('Amanda Costa', 'amanda.costa@yahoo.com', 'S', 123987, 9),
('Larissa Martins', 'larissa.martins@hotmail.com', 'S', 210987, 8),
('Carolina Santos', 'carolina.santos@gmail.com', 'N', 543210, 2),
('Beatriz Oliveira', 'beatriz.oliveira@yahoo.com', 'N', 345678, 4),
('Isabela Pereira', 'isabela.pereira@gmail.com', 'N', 765432, 6),
('Juliana Lima', 'juliana.lima@hotmail.com', 'N', 789012, 1),
('Gabriela Costa', 'gabriela.costa@yahoo.com', 'N', 987654, 2),
('Mariana Souza', 'mariana.souza@gmail.com', 'N', 654321, 6),
('Clara Oliveira', 'clara.oliveira@hotmail.com', 'N', 321098, 3),
('Luana Martins', 'luana.martins@gmail.com', 'N', 210987, 8),
('Rafaela Silva', 'rafaela.silva@yahoo.com', 'N', 654321, 6),
('Daniela Pereira', 'daniela.pereira@hotmail.com', 'N', 789012, 1),
('Tatiane Costa', 'tatiane.costa@gmail.com', 'N', 987654, 2),
('Elaine Santos', 'elaine.santos@hotmail.com', 'N', 345678, 4),
('Patrícia Lima', 'patricia.lima@yahoo.com', 'N', 876543, 5),
('Renata Oliveira', 'renata.oliveira@gmail.com', 'N', 543210, 2);

select * from categoria;

-- SELECT *
-- FROM produtos
-- INNER JOIN categoria ON produtos.idprodutos = categoria.idcategoria
-- INNER JOIN usuario on produtos.idprodutos = usuario.idusuario;
